/* oxlint-disable next/no-html-link-for-pages -- Native navigation avoids the deployed Vinext client-router failure. */
import { LinkArrow } from '@/components/link-arrow';
import { pageMetadata } from '@/lib/metadata';

export const metadata = pageMetadata('For hiring teams', '/hire', 'Oluwaseyi David is a Lagos-based brand designer and strategist with experience across independent practice, in-house design and building a business. Open to full-time brand design roles.');

const experience = [
  { date: '2022–present', title: 'Independent Brand Strategist & Designer', company: 'Independent practice', scope: 'Working with founders and growing businesses from discovery and positioning through identity systems, campaigns and final delivery.' },
  { date: '2022–2024', title: 'In-house Designer', company: 'MyShopLauncher', scope: 'Brand and marketing design for an e-commerce SaaS platform, across campaigns, email, social content and customer-facing communication.' },
  { date: '2023', title: 'Co-founder · Brand & Product Lead', company: 'Deliveryguy', scope: 'Brand strategy, visual identity and product experience for a logistics platform, including rider discovery and delivery coordination.' },
];

export default function HirePage() {
  return <main id="main" className="hire-page">
    <section className="page-intro"><p className="eyebrow">For hiring teams</p><h1>Thoughtful decisions.<br /><em>Work that holds together.</em></h1><p className="intro-summary">I’m a brand designer and strategist with 7+ years of experience, working from positioning through visual identity and everyday applications. I bring experience from independent practice, an in-house team and co-founding a business, with a close understanding of the decisions behind the work.</p><p className="hire-availability">Open to full-time brand design roles. Freelance enquiries are welcome too.</p><div className="hire-actions"><a className="pill-link" href="/downloads/oluwaseyi-david-cv.pdf" download>Download my CV <span aria-hidden="true"><LinkArrow /></span></a><a className="text-link" href="mailto:hello@oluwaseyidavid.com">Let’s talk <span aria-hidden="true"><LinkArrow /></span></a></div></section>
    <section className="relationship-section"><p className="eyebrow">Experience</p><div className="hire-timeline">{experience.map(role => <article key={role.company}><p className="eyebrow">{role.date} · {role.company}</p><h2>{role.title}</h2><p>{role.scope}</p></article>)}</div></section>
    <section className="relationship-section"><p className="eyebrow">How I contribute</p><div><h2>From the first question<br /><em>to the finished system.</em></h2><h3 className="story-subheading">What I lead</h3><p>In my independent practice, I lead projects from discovery and positioning through visual identity, design systems and delivery. I present the thinking directly to founders and decision-makers.</p><h3 className="story-subheading">How I collaborate</h3><p>I also work within an existing direction and alongside other specialists. For Schlepp, Boxless Studio developed the verbal identity; I translated it into the visual identity and guidelines.</p><a className="text-link" href="/work/schlepp">See the Schlepp case study <span aria-hidden="true"><LinkArrow /></span></a></div></section>
    <section className="capabilities"><div><p className="eyebrow">Practice & tools</p><h2>A clear idea.<br /><em>Across different formats.</em></h2></div><div className="capability-list"><div><div><h3>Disciplines</h3><p>Brand strategy, visual identity, creative and art direction, brand systems, campaigns, motion, digital and presentation design.</p></div></div><div><div><h3>Tools</h3><p>Illustrator, Photoshop, InDesign, After Effects, Premiere Pro and Figma. Generative AI creative tools where they support the work.</p></div></div><div><div><h3>Education</h3><p>B.Eng. Marine & Offshore Engineering<br />Federal University of Petroleum Resources, Effurun · 2021</p></div></div></div></section>
    <section className="relationship-section"><p className="eyebrow">Start a conversation</p><div><h2>Tell me about<br /><em>your team.</em></h2><p>I’m based in Lagos, Nigeria. If you’re looking for a designer who can connect the thinking with the making, I’d like to hear about the role.</p><a className="text-link" href="mailto:hello@oluwaseyidavid.com">hello@oluwaseyidavid.com <span aria-hidden="true"><LinkArrow /></span></a><div><a className="text-link" href="/work">View selected work <span aria-hidden="true"><LinkArrow /></span></a></div></div></section>
  </main>;
}
